### ISSUE TITLE
Babel plugin error: ".strict is not a valid Plugin property"

### ISSUE THREAD

**Issue by frederikhors** [lukeed/obj-str#10]
I'm using this lib but only today I found it's babel plugin: amazing!

With [@rollup/plugin-babel](https://github.com/rollup/plugins/tree/master/packages/babel) it throws using it like this:

- rollup.config.js:

```js
import { babel } from "@rollup/plugin-babel";
import { terser } from "rollup-plugin-terser";

export default {
  //...
  plugins: [
    babel({
      babelHelpers: "bundled",
      extensions: [".svelte"],
      plugins: ["optimize-objstr", { "strict": true }],
    }),
  ],
};
```

the error:

```
Error: [BABEL] C:\a\src\App.svelte: .strict is not a valid Plugin property
- Maybe you meant to use
"plugin": [
  ["optimize-objstr", {
  "strict": true
}]
]
To be a valid plugin, its name and options should be wrapped in a pair of brackets
    at C:\a\node_modules\@babel\core\lib\config\validation\plugins.js:65:42
    at Array.forEach (<anonymous>)
    at validatePluginObject (C:\a\node_modules\@babel\core\lib\config\validation\plugins.js:54:20)
    at C:\a\node_modules\@babel\core\lib\config\full.js:261:55
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\a\node_modules\@babel\core\lib\gensync-utils\async.js:16:3)
    at Generator.next (<anonymous>)
    at step (C:\a\node_modules\gensync\index.js:261:32)
    at evaluateAsync (C:\a\node_modules\gensync\index.js:291:5)
    at Function.errback (C:\a\node_modules\gensync\index.js:113:7)
```

**Why?**

**Comment by lukeed** [comment]
When  you define Babel plugin (or preset) options, you have to use an extra `[]` nesting, even if you only have one:

```diff
export default {
  //...
  plugins: [
    babel({
      babelHelpers: "bundled",
      extensions: [".svelte"],
--      plugins: ["optimize-objstr", { "strict": true }],
++      plugins: [
++        ["optimize-objstr", { "strict": true }]
++      ],
    }),
  ],
};

**Comment by frederikhors** [comment]
It works! Thanks!
